[Fix] Cell's output with no data
m-rossi/jupyter-docx-bundler pull request #63
Opened 2020-12-10 17:30 UTC by TanguyFi

**Cell's output with no data**

A notebook with a cell containing a `print` instruction fails to export because the cell's output does not contain `data` key. This PR fix it

**Checklist**

- [ ] Tests have passed
- [ ] New code is covered with tests

2020-12-10 19:20 UTC, m-rossi commented
@TanguyFi thanks for your contribution. I was not aware of this issue.

Don't mind the failing tests, they do sometimes. I was unable to track down why. I restarted CI.

2020-12-11 09:49 UTC, TanguyFi commented
@m-rossi Tested on my environment, it's ok ! 👌  Could you merge this and do a new release ? 🙂

2020-12-11 09:55 UTC, m-rossi commented
Please add the test I described above. If that's in I will happily merge.

2020-12-11 10:10 UTC, m-rossi requested changes

2020-12-11 10:11 UTC, m-rossi commented
Looks like I have forgotten to press submit, until now it was only visible to me.

2020-12-11 14:05 UTC, TanguyFi commented
Seems good ? 🙂

2020-12-11 15:07 UTC, m-rossi commented
In general: I already have a fixture with simple print statements: https://github.com/m-rossi/jupyter-docx-bundler/blob/master/jupyter_docx_bundler/tests/conftest.py#L227-L252 The related test also checks if the output is kept although the input is hided.

Is your error may a combination of print statements with pandas-html-tables?

2020-12-11 15:11 UTC, TanguyFi commented
Yes, exactly but more generally  when a cell implies a `print` but a return an output with `data` key.

2020-12-11 15:16 UTC, m-rossi commented
Ok, understood. This must be related to code I introduced to import pandas-html-tables.

In the fix you created is the pandas-table a nice world table after exporting?

2020-12-11 15:30 UTC, TanguyFi commented
I think everything is ok: 

![image](https://user-images.githubusercontent.com/65895282/101922281-2e3d4080-3bce-11eb-8fc7-db9ba7a47859.png)

2020-12-11 16:03 UTC, m-rossi requested changes

2020-12-11 16:03 UTC, m-rossi commented on jupyter_docx_bundler/tests/conftest.py
> +@pytest.fixture()
We do not need an extra test for this error. Please remove.

2020-12-11 16:03 UTC, m-rossi commented on jupyter_docx_bundler/converters.py
>          if 'outputs' in cell and any(['data' in output for output in cell['outputs']]):
Please remove the additional check for data in this if-clause. We do this better in your code below.

2020-12-11 16:03 UTC, m-rossi commented on jupyter_docx_bundler/tests/test_converters.py
> +def test_print_with_html(tmpdir, print_with_html_notebook):
We do not need an extra fixture. Please remove.

2020-12-11 16:27 UTC, m-rossi approved these changes

2020-12-11 16:29 UTC, m-rossi commented
Thanks @TanguyFi for this bugfix, will merge and release in the next hours.

2020-12-11 17:07 UTC, merged